sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNNXeDYNj3J2PGw1rPo
    access-key-secret: 3niOOMxGCuQGj4ZIbQ2TdomTDYNXUc
    bucket-name: tyweb-tlias
